### ISSUE TITLE
"error":"16: mandatory-script-verify-flag-failed

### ISSUE THREAD

**Issue by malpais** [deanmlittle/21e8miner#3]
{"error":"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"}

Signed transaction and received this error. New here. Any idea?

**Comment by relayking** [comment]
Float math produces wrong satoshi amount. You should parse transaction hex instead of relying on whatonchain parsed tx api.

**Comment by deanmlittle** [comment]
Fixed by @Breavyn
